      MODULE PARTICLE_DATA

        IMPLICIT NONE
        SAVE
        INTEGER PARTI

        REAL,ALLOCATABLE::RXPA(:),RYPA(:),RZPA(:)
        REAL,ALLOCATABLE::U2DM(:),U3DM(:),U4DM(:)
        REAL,ALLOCATABLE::MASAP(:),KERNEL(:)
        REAL,ALLOCATABLE::ABVC(:)

      END MODULE PARTICLE_DATA
